[model]
family = "classical_local_stochastic_volatility"

[general]
num_paths = 8192
seed = 42
log_price = true
plot_variance = false

[parameters]
noise_timesteps = 56
rde_timesteps = 256

v_0 = 0.04
rho = -0.3
s_0 = 1.0

xi_0 = 0.2
xi_s = 0.001
xi_v = 0.1

lambda_ = 1.0
v_bar = 0.04
f2_0 = 0.08
f2_1 = 0.05
