[model]
family = "heston"

[general]
num_paths = 512
seed = 42
log_price = true
plot_variance = false

[parameters]
noise_timesteps = 56
rde_timesteps = 256

v_0 = 0.04
rho = -0.7
nu = 0.5
lambda_ = 1.5
v_bar = 0.04
s_0 = 1.0
